const LESSONS_DATA = {
  1: {
    id: 1,
    title: "Tell me about yourself",
    emoji: "👤",
    audio: "topic1.mp3",
    sentences: [
      ["I walked into the English club a few minutes late.",                             0.00,  3.88],
      ["Great. Perfect timing.",                                                         3.88,  6.22],
      ["The club owner looked at me and smiled.",                                        6.22,  9.12],
      ["Hi! You must be new.",                                                           9.12, 11.30],
      ["Yes, I am, I said, trying not to sound too nervous.",                           11.30, 15.62],
      ["Welcome! Why don't you go ahead and introduce yourself?",                       15.62, 19.10],
      ["Of course. Right away.",                                                        19.10, 21.22],
      ["I took a deep breath.",                                                         21.22, 23.28],
      ["Hi everyone, I'm Rose.",                                                        23.28, 25.70],
      ["I'm currently living in Da Nang.",                                              25.70, 28.32],
      ["I'm a student. I love learning languages.",                                     28.32, 31.92],
      ["The club owner nodded.",                                                        31.92, 33.48],
      ["That's great. What made you join us?",                                          33.48, 36.28],
      ["Good question.",                                                                36.28, 38.14],
      ["Well, I said, I realized that every time someone says,",                        38.14, 42.68],
      ["Tell me about yourself, my brain just freezes.",                                42.68, 46.86],
      ["So I figured it was time to step out of my comfort zone.",                      46.86, 51.10],
      ["No one laughed.",                                                               51.10, 52.44],
      ["One member said, trust me, we've all been there.",                              52.44, 56.38],
      ["I smiled.",                                                                     56.38, 57.62],
      ["Okay, that makes me feel better.",                                              57.62, 60.20],
      ["By the end of the session, I was chatting with two new friends like it was no big deal.", 60.20, 66.00],
      ["That night, I thought about something simple.",                                 66.00, 69.58],
      ["You don't need perfect grammar to connect with people.",                        69.58, 72.96],
      ["You just need the courage to speak up.",                                        72.96, 75.60],
    ]
  },
  2: {
    id: 2,
    title: "A Small Speech for Women's Day",
    emoji: "🌸",
    audio: "topic2.mp3",
    sentences: [
  ["Story. A Small Speech for Women's Day.",                       0.26,   3.55],
  ["A week later, I went back to the English club.",               4.57,   7.30],
  ["This time, I arrived early.",                                  7.83,   9.88],
  ["The room felt warm and friendly.",                            10.51,  12.87],
  ["The club owner clapped her hands.",                           13.46,  15.19],
  ["Alright everyone! Today's theme is Women's Day.",             15.75,  19.73],
  ["She smiled.",                                                 20.00,  21.00],
  ["Each person will say a few sentences to celebrate a woman in their life.", 21.00, 26.50],
  ["Oh. A mini speech.",                                          27.00,  29.00],
  ["My heart was beating a little faster.",                       29.02,  32.00],
  ["But not like last week.",                                     32.00,  33.30],
  ["I took a deep breath.",                                        33.35,  35.50],
  ["Again.",                                                       35.55,  39.00],
  ["The first few members spoke.",                                39.01,  42.00],
  ["One talked about her mother.",                                42.01,  44.00],
  ["Another talked about his teacher.",                           44.01,  46.00],
  ["Then it was my turn.",                                        46.01,  47.50],
  ["Hi everyone, I said.",                                        47.50,  48.50],
  ["My name is Rose.",                                            48.50,  49.50],
  ["This Women's Day, I want to say thank you to my mom.",        49.55,  51.50],
  ["She is not famous.",                                          52.00,  53.50],
  ["She is not rich.",                                            54.00,  55.50],
  ["But she is the strongest woman I know.",                      56.00,  58.50],
  ["She taught me to be kind.",                                   59.00,  61.00],
  ["She taught me to keep learning.",                             61.50,  63.50],
  ["And she always believes in me.",                              64.00,  66.00],
  ["I paused for a second.",                                      66.50,  68.50],
  ["And today, I also want to celebrate all the women here.",     69.00,  73.00],
  ["Happy Women's Day.",                                          73.50,  75.50],
  ["The room became quiet.",                                      76.00,  77.50],
  ["Then people started clapping.",                               78.00,  80.00],
  ["Not loud. But warm.",                                         80.50,  82.50],
  ["One member said, that was wonderful.",                        83.00,  85.50],
  ["I smiled.",                                                   86.00,  87.50],
  ["Not nervous this time.",                                      88.00,  89.50],
  ["On the way home, I thought about something again.",           90.00,  93.50],
  ["Speaking English is not only about vocabulary.",              94.00,  97.00],
  ["Sometimes, it's about speaking from the heart.",              97.50, 101.50]
]
      },
  3: {
    id: 3,
    title: "Talking about Family",
    emoji: "👨‍👩‍👧‍👦",
    audio: "topic3.mp3",
    sentences: [
      ["Story. Talking about Family.",                                                   0.26,  2.04],
      ["A week later, I went back to the English club.",                                 2.53,  5.71],
      ["This was my third time!",                                                        6.17,  8.17],
      ["When I opened the door, I saw many familiar faces.",                             8.79, 12.49],
      ["Some people waved at me and said, Hi Rose!",                                   13.02, 15.18],
      ["I gave them a big smile and waved back.",                                       15.55, 16.44],
      ["Then I found a seat and sat down.",                                             17.03, 20.00],
      ["Soon, the club owner stood up and clapped her hands.",                          20.64, 22.65],
      ["Clap, clap, clap!",                                                             23.33, 27.15],
      ["Alright everyone! she said.",                                                   27.59, 28.86],
      ["Tonight, let's talk about our families.",                                       29.52, 31.35],
      ["Everyone nodded and smiled.",                                                   31.88, 34.66],
      ["I liked this topic a lot.",                                                     35.38, 37.24],
      ["It made me feel warm inside.",                                                  37.90, 39.75],
      ["One man stood up and said,",                                                    40.15, 42.01],
      ["My family is small.",                                                           42.87, 44.74],
      ["I live with my wife and my son.",                                               45.36, 46.92],
      ["Every night, we eat dinner together and talk about our day.",                   47.26, 49.47],
      ["Then the club owner looked at me.",                                             50.09, 53.82],
      ["Rose, would you like to share?",                                                54.59, 56.80],
      ["I stood up slowly and took a deep breath.",                                     57.46, 59.47],
      ["Hi everyone! My name is Rose, I said.",                                         60.23, 63.09],
      ["My family isn't very big, but it is full of love.",                             64.13, 65.15],
      ["I live with my mommy, my daddy, and my little sister.",                         65.42, 67.62],
      ["My mommy is lovely.",                                                           68.26, 70.08],
      ["She loves taking photos of us.",                                                70.37, 72.14],
      ["My dad is quiet, but he takes very good care of our family.",                   72.68, 74.20],
      ["And my little sister?",                                                         74.49, 75.31],
      ["She is so funny!",                                                              75.62, 76.65],
      ["She always makes us giggle.",                                                   77.48, 81.46],
      ["I paused for a moment and continued.",                                          82.13, 87.97],
      ["On weekends, we often visit my grandma and grandpa.",                           88.43, 90.27],
      ["We sit together, drink tea, and talk about many things.",                       90.52, 92.27],
      ["My grandma sometimes tells old family stories.",                                92.98, 94.29],
      ["And my grandpa always asks, Are you eating well?",                              94.55, 95.24],
      ["Everyone in the room laughed softly.",                                          95.99, 99.79],
      ["Then I said,",                                                                 100.30, 104.71],
      ["At night, our family has a little habit.",                                     105.28, 108.82],
      ["Before bed, we often read books together.",                                    109.14, 112.77],
      ["Sometimes we read quietly.",                                                   113.49, 115.84],
      ["Sometimes we share the funny parts of the story.",                             116.58, 117.27],
      ["It's a simple moment, but I love it the most.",                                117.75, 118.42],
      ["I looked around the room and felt happy.",                                     118.77, 120.66],
      ["For me, family is a safe place.",                                              121.27, 124.34],
      ["It's a place where people listen to you.",                                     124.90, 127.06],
      ["And it's a place where love grows every day.",                                 127.58, 130.74],
      ["Thank you!",                                                                   131.38, 132.69],
      ["When I sat down, the room was quiet for a moment.",                            132.95, 134.63],
      ["Then someone said, what a beautiful family!",                                  135.28, 137.87],
      ["Another person said, I want to read books with my family too!",               138.67, 141.58],
      ["I smiled.",                                                                    142.09, 144.29],
      ["On the way home, I thought about it again.",                                   144.86, 148.02],
      ["Families don't have to be perfect.",                                           148.82, 151.24],
      ["Sometimes, it's just the little things.",                                      151.61, 153.53],
      ["Sharing a meal, telling a joke, or reading a story before bed.",               154.09, 157.50],
      ["And maybe, those small moments are what make a family truly special.",         158.10, 166.90],
    ]
  },
  4: {
    id: 4,
    title: "Inviting a Guest Home",
    emoji: "🏠",
    audio: "Topic4.mp3",
    sentences: [
      ["After the sharing time, the club owner smiled at me.",                               0.00,  4.40],
      ["Rose, she said, your family sounds interesting.",                                    4.40,  9.24],
      ["I felt a little shy, but I smiled.",                                                 9.24, 13.28],
      ["Thank you!",                                                                        13.28, 14.62],
      ["Then she asked, do you live near here?",                                            14.62, 18.82],
      ["Yes, I said. My house is not very far from the club.",                              18.82, 24.40],
      ["She laughed softly.",                                                               24.40, 26.42],
      ["Really? I would love to see your home someday.",                                    26.42, 30.26],
      ["I thought for a moment.",                                                           30.26, 32.56],
      ["Then I said, why don't you visit my house this weekend?",                           32.56, 37.64],
      ["Her eyes lit up.",                                                                  37.64, 40.00],
      ["That sounds lovely!",                                                               40.00, 41.78],
      ["On Saturday afternoon, she came to my house.",                                      41.78, 46.08],
      ["When she arrived, I opened the door and waved.",                                    46.08, 50.02],
      ["Welcome to my house!",                                                              50.02, 52.02],
      ["She smiled and said, thank you for inviting me, Rose.",                             52.02, 56.88],
      ["She looked at the building and said, oh, this house looks quite big.",              56.88, 63.14],
      ["I nodded and explained, yes, my family lives here, but we also rent out some rooms.", 63.14, 71.14],
      ["I began to introduce the house.",                                                   71.14, 74.28],
      ["This is the first floor, I said. A small shop rents this space.",                   74.28, 80.60],
      ["They sell clothes.",                                                                80.60, 82.28],
      ["Then I continued. On the upper floors there are several rooms.",                    82.28, 89.82],
      ["Some students rent rooms here and some small families live here too.",              89.82, 96.00],
      ["Then I said, come, let me show you where my family lives.",                         96.00, 103.50],
      ["We walked upstairs.",                                                              103.50, 106.00],
      ["This is our living room, I explained.",                                            106.00, 110.44],
      ["In the evening, my parents, my sister, and I often sit here and talk.",            110.44, 116.00],
      ["Then I pointed to another room. This is our kitchen.",                             116.00, 121.00],
      ["My mom cooks many delicious meals here.",                                          121.00, 127.66],
      ["Over there is our bathroom. It's small, but we always keep it clean.",             127.66, 132.00],
      ["And we have two bedrooms. They are small, but very cozy.",                         132.00, 136.00],
      ["Near the window, there was a small table with some books.",                        136.00, 140.00],
      ["This is my favorite place, I said. I like to sit here and read.",                  140.00, 144.74],
      ["The club owner smiled warmly.",                                                    144.74, 148.00],
      ["That sounds like a very peaceful moment.",                                         148.00, 153.16],
      ["After the tour, we sat in the living room and drank some tea.",                    153.16, 158.50],
      ["The club owner said, Rose, you introduced your house very clearly in English.",    158.50, 163.50],
      ["I laughed a little.",                                                              163.50, 165.50],
      ["I'm still learning, I said, but I like practicing English with real-life things.", 165.50, 168.74],
      ["She nodded. That's the best way to learn.",                                        168.74, 177.40],
      ["Then she said, next week at the club, maybe everyone can talk about their houses.", 177.40, 183.80],
      ["My eyes lit up. That sounds fun!",                                                 183.80, 186.18],
      ["And suddenly I realized something.",                                               186.18, 189.00],
      ["Sometimes, the best English lesson is simply sharing your life, your home, and your stories with others.", 189.00, 195.54],
    ]
  },
  5: {
    id: 5,
    title: "Back Again!",
    emoji: "🔄",
    audio: "topic5.mp3",
    sentences: [
      ["Story. Back Again.",                                                              0.00,  0.91],
      ["One week.",                                                                       1.28,  3.46],
      ["That's how long I had been away from the club.",                                  4.12,  6.23],
      ["I pushed open the door and stepped inside.",                                      6.70,  8.39],
      ["A few people looked up and smiled.",                                              8.76,  9.38],
      ["Someone said, Rose! You're back!",                                                9.83, 11.09],
      ["I gave a little wave.",                                                           11.66, 12.53],
      ["Sorry for disappearing, I said.",                                                 13.22, 14.95],
      ["Some family stuff came up.",                                                      15.23, 16.52],
      ["The club owner nodded warmly.",                                                   17.08, 18.71],
      ["We missed you. Glad you're here tonight.",                                        19.01, 20.90],
      ["That small welcome.",                                                             21.67, 23.08],
      ["It meant more than I expected.",                                                  23.60, 25.21],
      ["She clapped her hands.",                                                          25.80, 26.68],
      ["Alright, everyone.",                                                              27.04, 29.60],
      ["Tonight's topic is: How do you keep English in your daily life?",                 30.00, 32.32],
      ["Not just study. Just... life.",                                                   32.82, 34.19],
      ["Interesting.",                                                                    34.74, 35.12],
      ["I had been thinking about this lately.",                                          35.94, 36.59],
      ["One member said,",                                                                37.13, 38.69],
      ["I switched my phone to English.",                                                 39.36, 40.30],
      ["It feels small, but I pick up new words without even trying.",                    40.75, 42.65],
      ["Another said, I talk to myself in English on the way to work.",                   42.96, 46.29],
      ["I just describe what I see.",                                                     46.92, 47.73],
      ["A few people laughed quietly.",                                                   48.31, 50.40],
      ["Honestly, same, someone admitted.",                                               50.71, 52.17],
      ["Then it was my turn.",                                                            52.87, 54.62],
      ["Last week, I barely used English at all, I said.",                                55.04, 57.26],
      ["I was busy. I kept telling myself, I'll do it tomorrow.",                         57.85, 60.51],
      ["I paused.",                                                                       60.81, 63.06],
      ["But tomorrow kept moving further away.",                                          63.64, 64.30],
      ["I looked around the room.",                                                       64.61, 67.16],
      ["Coming here, showing up every week, that's my habit.",                            67.81, 68.35],
      ["Not perfect. I missed one week.",                                                 69.15, 71.54],
      ["But I don't want to quit.",                                                       72.17, 73.08],
      ["I just want to keep showing up.",                                                 73.83, 75.91],
      ["The room was quiet for a moment.",                                                76.29, 77.35],
      ["The club owner smiled.",                                                          77.87, 79.71],
      ["A habit is something you build every day.",                                       80.22, 81.44],
      ["But missing a few days doesn't erase it.",                                        81.86, 83.60],
      ["You just pick it up again, no guilt, no drama.",                                  84.47, 86.12],
      ["On the way home, I turned that over in my mind.",                                 86.71, 87.78],
      ["A habit isn't ruined by a bad week.",                                             88.53, 90.85],
      ["It's ruined by deciding not to go back.",                                         91.36, 93.51],
      ["Tonight, I went back.",                                                           94.01, 96.81],
      ["And that felt like enough.",                                                      97.85, 100.55],
    ]
  },
  6: {
    id: 6,
    title: "A Day at the Beach",
    emoji: "🏖️",
    audio: "topic6.mp3",
    sentences: [
      ["It was a beautiful Sunday afternoon.",                                             0.26,  3.51],
      ["I went to the beach with my parents and my little sister.",                        4.05,  7.71],
      ["The sun was shining, and the waves sounded so relaxing.",                          8.16,  9.73],
      ["While my family was playing together on the sand,",                               10.00, 12.78],
      ["I noticed a tourist nearby.",                                                     13.51, 16.88],
      ["She was helping her little boy build a sandcastle.",                              17.22, 19.46],
      ["I remembered the club owner's words from last week.",                             19.95, 23.74],
      ["Make English a daily habit.",                                                     24.48, 28.13],
      ["I took a deep breath and walked over.",                                           28.62, 31.14],
      ["Time to practice.",                                                               31.73, 33.08],
      ["Hi there! That is a very impressive sandcastle.",                                 33.48, 34.56],
      ["The woman looked up from the sand and smiled warmly.",                            35.08, 36.54],
      ["Oh, thank you!",                                                                  37.22, 37.88],
      ["He's been working on it all afternoon.",                                          38.34, 41.47],
      ["I'm Sarah, by the way.",                                                          42.12, 46.15],
      ["Nice to meet you, Sarah. I'm Rose.",                                              46.68, 51.60],
      ["He looks like he's having a great time.",                                         52.15, 53.44],
      ["He really is.",                                                                   53.84, 54.76],
      ["The beach here is amazing.",                                                      55.23, 57.76],
      ["I wanted to keep the conversation going, so I asked a simple question.",          58.29, 61.34],
      ["Are you visiting Da Nang for a holiday?",                                         62.03, 64.88],
      ["Yes, we are! We're visiting from New Zealand.",                                   65.19, 67.45],
      ["It's our first time in Vietnam.",                                                 68.06, 70.62],
      ["Welcome! How are you liking it so far?",                                          71.19, 75.83],
      ["We love it.",                                                                     76.38, 77.08],
      ["The food is delicious, and everyone is so friendly.",                             77.47, 79.31],
      ["What about you? Do you live here?",                                               79.83, 84.91],
      ["Yes, I was born here.",                                                           85.18, 86.87],
      ["I'm actually here with my family today.",                                         87.54, 89.26],
      ["My little sister is just over there, playing in the sand.",                       89.72, 92.26],
      ["That sounds like fun!",                                                           92.73, 96.63],
      ["It's so nice to spend a Sunday with family.",                                     97.21, 98.51],
      ["It really is.",                                                                   99.10, 103.25],
      ["We chatted for a few more minutes about local seafood.",                          103.88, 104.96],
      ["When I said goodbye, I felt a warm sense of pride.",                              105.56, 109.55],
      ["On my way back to my family, I realized something.",                              110.06, 114.14],
      ["Starting a conversation isn't as scary as I thought.",                            114.85, 116.85],
      ["And keeping it going?",                                                           117.25, 118.61],
      ["You just need to show a little interest in the other person.",                    119.05, 123.22],
      ["Sometimes, a simple question can open the door to a great chat.",                 123.52, 129.26],
    ]
  },
   7: {
    id: 7,
    title: "A Trip to Con Market",
    emoji: "🛒",
    audio: "topic7.mp3",
    sentences: [
      ["A few days later, my mom sent me to Con Market to buy some fruit.",                  0.00,  4.20],
      ["It was crowded and noisy, as usual.",                                                4.20,  6.80],
      ["I saw Sarah and her family at a food stall.",                                        6.80,  9.60],
      ["Her family was busy eating, but Sarah was standing aside, looking at the snack stalls with a bit of hesitation.", 9.60, 14.80],
      ["Rose: Sarah? Hi! What a surprise!",                                                 14.80, 17.40],
      ["Sarah: Oh, Rose! Hi! What a small world! It's so good to see you again.",           17.40, 22.00],
      ["Rose: Good to see you too! How's it going? The market is pretty crazy today, huh?", 22.00, 27.20],
      ["Sarah: Yeah, it's a bit much!",                                                     27.20, 29.80],
      ["But my family is over there—they're having a great time trying the local food.",     29.80, 33.80],
      ["I want to buy some snacks to take home, but everything looks great, and there are so many options!", 33.80, 38.80],
      ["I'm not sure which one is the best.",                                               38.80, 41.60],
      ["Rose: I totally understand.",                                                       41.60, 43.40],
      ["Well, these are Anatta soft-dried bananas.",                                        43.40, 46.20],
      ["They're a local favorite—really sweet and healthy.",                                46.20, 49.20],
      ["I buy them all the time.",                                                          49.20, 51.40],
      ["Sarah: Oh, they look good!",                                                        51.40, 53.40],
      ["But I don't see any price tags.",                                                   53.40, 56.20],
      ["Should I just hand her some cash and hope for the best?",                           56.20, 60.20],
      ["Rose: In local markets, it's better to ask first.",                                 60.20, 64.20],
      ["You might even get a better deal if you buy a few packs.",                          64.20, 68.40],
      ["Do you want to try asking in Vietnamese?",                                          68.40, 71.40],
      ["Sarah: I'd love to, but I don't know how!",                                        71.40, 74.60],
      ["Rose: It's easy.",                                                                  74.60, 76.20],
      ["Just say: Bao nhiêu tiền?",                                                        76.20, 79.40],
      ["Sarah: Bao... nhiêu... tiền? Did I get that right?",                               79.40, 83.80],
      ["Rose: Perfect!",                                                                   83.80, 85.40],
      ["Go ahead, I'm right here if you need me.",                                         85.40, 88.60],
      ["Sarah: That was actually fun!",                                                    88.60, 90.80],
      ["Thanks, Rose.",                                                                    90.80, 92.40],
      ["I'm so glad I ran into you.",                                                      92.40, 95.00],
      ["Rose: Me too. I'm just happy I could help.",                                       95.00, 98.00],
      ["I helped Sarah pick out her gifts, and we swapped numbers.",                       98.00, 102.20],
      ["On the way home, I realized something simple: Speaking a language isn't just about grammar.", 102.20, 107.60],
      ["It's about showing up, helping out, and making a connection.",                    107.60, 114.00],
    ]
  }
};
