const LESSONS_DATA = {
  1: {
    id: 1,
    title: "Tell me about yourself",
    emoji: "👤",
    audio: "topic1.mp3",
    sentences: [
      ["I walked into the English club a few minutes late.",                             0.00,  3.88],
      ["Great. Perfect timing.",                                                         3.88,  6.22],
      ["The club owner looked at me and smiled.",                                        6.22,  9.12],
      ["Hi! You must be new.",                                                           9.12, 11.30],
      ["Yes, I am, I said, trying not to sound too nervous.",                           11.30, 15.62],
      ["Welcome! Why don't you go ahead and introduce yourself?",                       15.62, 19.10],
      ["Of course. Right away.",                                                        19.10, 21.22],
      ["I took a deep breath.",                                                         21.22, 23.28],
      ["Hi everyone, I'm Rose.",                                                        23.28, 25.70],
      ["I'm currently living in Da Nang.",                                              25.70, 28.32],
      ["I'm a student. I love learning languages.",                                     28.32, 31.92],
      ["The club owner nodded.",                                                        31.92, 33.48],
      ["That's great. What made you join us?",                                          33.48, 36.28],
      ["Good question.",                                                                36.28, 38.14],
      ["Well, I said, I realized that every time someone says,",                        38.14, 42.68],
      ["Tell me about yourself, my brain just freezes.",                                42.68, 46.86],
      ["So I figured it was time to step out of my comfort zone.",                      46.86, 51.10],
      ["No one laughed.",                                                               51.10, 52.44],
      ["One member said, trust me, we've all been there.",                              52.44, 56.38],
      ["I smiled.",                                                                     56.38, 57.62],
      ["Okay, that makes me feel better.",                                              57.62, 60.20],
      ["By the end of the session, I was chatting with two new friends like it was no big deal.", 60.20, 66.00],
      ["That night, I thought about something simple.",                                 66.00, 69.58],
      ["You don't need perfect grammar to connect with people.",                        69.58, 72.96],
      ["You just need the courage to speak up.",                                        72.96, 75.60],
    ]
  },
  2: {
    id: 2,
    title: "A Small Speech for Women's Day",
    emoji: "🌸",
    audio: "topic2.mp3",
    sentences: [
      ["Story. A Small Speech for Women's Day.",                                        0.26,  3.55],
      ["A week later, I went back to the English club.",                                4.57,  7.30],
      ["This time, I arrived early.",                                                   7.83,  9.88],
      ["The room felt warm and friendly.",                                             10.51, 12.87],
      ["The club owner clapped her hands.",                                            13.46, 15.19],
      ["Alright everyone! Today's theme is Women's Day.",                             15.75, 19.73],
      ["Oh. A mini speech.",                                                           20.43, 21.11],
      ["My heart was beating a little faster.",                                        21.62, 26.36],
      ["But not like last week.",                                                      27.39, 29.40],
      ["I took a deep breath. Again.",                                                 30.08, 32.22],
      ["The first few members spoke.",                                                 32.50, 33.69],
      ["One talked about her mother.",                                                 34.27, 35.41],
      ["Another talked about his teacher.",                                            36.15, 36.59],
      ["Then it was my turn.",                                                         37.69, 39.42],
      ["Hi everyone, I said.",                                                         39.98, 41.52],
      ["My name is Rose.",                                                             42.06, 43.85],
      ["This Women's Day, I want to say thank you to my mom.",                        44.32, 45.63],
      ["She is not famous.",                                                           46.51, 48.08],
      ["She is not rich.",                                                             48.56, 50.07],
      ["But she is the strongest woman I know.",                                       50.82, 52.03],
      ["She taught me to be kind.",                                                    52.44, 55.08],
      ["She taught me to keep learning.",                                              55.67, 56.96],
      ["And she always believes in me.",                                               57.29, 58.52],
      ["I paused for a second.",                                                       58.86, 61.68],
      ["And today, I also want to celebrate all the women here.",                      62.36, 64.05],
      ["Happy Women's Day.",                                                           64.30, 68.43],
      ["The room became quiet.",                                                       69.26, 70.40],
      ["Then people started clapping.",                                                70.97, 75.19],
      ["Not loud. But warm.",                                                          75.91, 77.42],
      ["One member said, that was wonderful.",                                         78.32, 79.92],
      ["I smiled.",                                                                    80.57, 82.08],
      ["Not nervous this time.",                                                       82.52, 83.92],
      ["On the way home, I thought about something again.",                            84.68, 87.91],
      ["Speaking English is not only about vocabulary.",                               88.69, 90.83],
      ["Sometimes, it's about speaking from the heart.",                               91.64, 101.58],
    ]
  },
  3: {
    id: 3,
    title: "Talking about Family",
    emoji: "👨‍👩‍👧‍👦",
    audio: "topic3.mp3",
    sentences:  [
      ["Story. Talking about Family.",                                                   0.26,  2.04],
      ["A week later, I went back to the English club.",                                 2.53,  5.71],
      ["This was my third time!",                                                        6.17,  8.17],
      ["When I opened the door, I saw many familiar faces.",                             8.79, 12.49],
      ["Some people waved at me and said, Hi Rose!",                                   13.02, 15.18],
      ["I gave them a big smile and waved back.",                                       15.55, 16.44],
      ["Then I found a seat and sat down.",                                             17.03, 20.00],
      ["Soon, the club owner stood up and clapped her hands.",                          20.64, 22.65],
      ["Clap, clap, clap!",                                                             23.33, 27.15],
      ["Alright everyone! she said.",                                                   27.59, 28.86],
      ["Tonight, let's talk about our families.",                                       29.52, 31.35],
      ["Everyone nodded and smiled.",                                                   31.88, 34.66],
      ["I liked this topic a lot.",                                                     35.38, 37.24],
      ["It made me feel warm inside.",                                                  37.90, 39.75],
      ["One man stood up and said,",                                                    40.15, 42.01],
      ["My family is small.",                                                           42.87, 44.74],
      ["I live with my wife and my son.",                                               45.36, 46.92],
      ["Every night, we eat dinner together and talk about our day.",                   47.26, 49.47],
      ["Then the club owner looked at me.",                                             50.09, 53.82],
      ["Rose, would you like to share?",                                                54.59, 56.80],
      ["I stood up slowly and took a deep breath.",                                     57.46, 59.47],
      ["Hi everyone! My name is Rose, I said.",                                         60.23, 63.09],
      ["My family isn't very big, but it is full of love.",                             64.13, 65.15],
      ["I live with my mommy, my daddy, and my little sister.",                         65.42, 67.62],
      ["My mommy is lovely.",                                                           68.26, 70.08],
      ["She loves taking photos of us.",                                                70.37, 72.14],
      ["My dad is quiet, but he takes very good care of our family.",                   72.68, 74.20],
      ["And my little sister?",                                                         74.49, 75.31],
      ["She is so funny!",                                                              75.62, 76.65],
      ["She always makes us giggle.",                                                   77.48, 81.46],
      ["I paused for a moment and continued.",                                          82.13, 87.97],
      ["On weekends, we often visit my grandma and grandpa.",                           88.43, 90.27],
      ["We sit together, drink tea, and talk about many things.",                       90.52, 92.27],
      ["My grandma sometimes tells old family stories.",                                92.98, 94.29],
      ["And my grandpa always asks, Are you eating well?",                              94.55, 95.24],
      ["Everyone in the room laughed softly.",                                          95.99, 99.79],
      ["Then I said,",                                                                 100.30, 104.71],
      ["At night, our family has a little habit.",                                     105.28, 108.82],
      ["Before bed, we often read books together.",                                    109.14, 112.77],
      ["Sometimes we read quietly.",                                                   113.49, 115.84],
      ["Sometimes we share the funny parts of the story.",                             116.58, 117.27],
      ["It's a simple moment, but I love it the most.",                                117.75, 118.42],
      ["I looked around the room and felt happy.",                                     118.77, 120.66],
      ["For me, family is a safe place.",                                              121.27, 124.34],
      ["It's a place where people listen to you.",                                     124.90, 127.06],
      ["And it's a place where love grows every day.",                                 127.58, 130.74],
      ["Thank you!",                                                                   131.38, 132.69],
      ["When I sat down, the room was quiet for a moment.",                            132.95, 134.63],
      ["Then someone said, what a beautiful family!",                                  135.28, 137.87],
      ["Another person said, I want to read books with my family too!",               138.67, 141.58],
      ["I smiled.",                                                                    142.09, 144.29],
      ["On the way home, I thought about it again.",                                   144.86, 148.02],
      ["Families don't have to be perfect.",                                           148.82, 151.24],
      ["Sometimes, it's just the little things.",                                      151.61, 153.53],
      ["Sharing a meal, telling a joke, or reading a story before bed.",               154.09, 157.50],
      ["And maybe, those small moments are what make a family truly special.",         158.10, 166.90],
    ]
  },
  4: {
    id: 4,
    title: "Inviting a Guest Home",
    emoji: "🏠",
    audio: "Topic4.mp3",
    sentences: [
      ["After the sharing time, the club owner smiled at me.",                               0.00,  4.40],
      ["Rose, she said, your family sounds interesting.",                                    4.40,  9.24],
      ["I felt a little shy, but I smiled.",                                                 9.24, 13.28],
      ["Thank you!",                                                                        13.28, 14.62],
      ["Then she asked, do you live near here?",                                            14.62, 18.82],
      ["Yes, I said. My house is not very far from the club.",                              18.82, 24.40],
      ["She laughed softly.",                                                               24.40, 26.42],
      ["Really? I would love to see your home someday.",                                    26.42, 30.26],
      ["I thought for a moment.",                                                           30.26, 32.56],
      ["Then I said, why don't you visit my house this weekend?",                           32.56, 37.64],
      ["Her eyes lit up.",                                                                  37.64, 40.00],
      ["That sounds lovely!",                                                               40.00, 41.78],
      ["On Saturday afternoon, she came to my house.",                                      41.78, 46.08],
      ["When she arrived, I opened the door and waved.",                                    46.08, 50.02],
      ["Welcome to my house!",                                                              50.02, 52.02],
      ["She smiled and said, thank you for inviting me, Rose.",                             52.02, 56.88],
      ["She looked at the building and said, oh, this house looks quite big.",              56.88, 63.14],
      ["I nodded and explained, yes, my family lives here, but we also rent out some rooms.", 63.14, 71.14],
      ["I began to introduce the house.",                                                   71.14, 74.28],
      ["This is the first floor, I said. A small shop rents this space.",                   74.28, 80.60],
      ["They sell clothes.",                                                                80.60, 82.28],
      ["Then I continued. On the upper floors there are several rooms.",                    82.28, 89.82],
      ["Some students rent rooms here and some small families live here too.",              89.82, 96.00],
      ["Then I said, come, let me show you where my family lives.",                         96.00, 103.50],
      ["We walked upstairs.",                                                              103.50, 106.00],
      ["This is our living room, I explained.",                                            106.00, 110.44],
      ["In the evening, my parents, my sister, and I often sit here and talk.",            110.44, 116.00],
      ["Then I pointed to another room. This is our kitchen.",                             116.00, 121.00],
      ["My mom cooks many delicious meals here.",                                          121.00, 127.66],
      ["Over there is our bathroom. It's small, but we always keep it clean.",             127.66, 132.00],
      ["And we have two bedrooms. They are small, but very cozy.",                         132.00, 136.00],
      ["Near the window, there was a small table with some books.",                        136.00, 140.00],
      ["This is my favorite place, I said. I like to sit here and read.",                  140.00, 144.74],
      ["The club owner smiled warmly.",                                                    144.74, 148.00],
      ["That sounds like a very peaceful moment.",                                         148.00, 153.16],
      ["After the tour, we sat in the living room and drank some tea.",                    153.16, 158.50],
      ["The club owner said, Rose, you introduced your house very clearly in English.",    158.50, 163.50],
      ["I laughed a little.",                                                              163.50, 165.50],
      ["I'm still learning, I said, but I like practicing English with real-life things.", 165.50, 168.74],
      ["She nodded. That's the best way to learn.",                                        168.74, 177.40],
      ["Then she said, next week at the club, maybe everyone can talk about their houses.", 177.40, 183.80],
      ["My eyes lit up. That sounds fun!",                                                 183.80, 186.18],
      ["And suddenly I realized something.",                                               186.18, 189.00],
      ["Sometimes, the best English lesson is simply sharing your life, your home, and your stories with others.", 189.00, 195.54],
    ]
  }
};
