const LESSONS_DATA = {
  1: {
    id: 1,
    title: "Tell me about yourself",
    emoji: "👤",
    audio: "topic1.mp3",
    sentences: [
      ["I walked into the English club a few minutes late.",                            0.0,   2.5],
      ["Great. Perfect timing.",                                                        2.5,   4.0],
      ["The club owner looked at me and smiled.",                                       4.0,   6.5],
      ["Hi! You must be new.",                                                          6.5,   8.0],
      ["Yes, I am. I said, trying not to sound too nervous.",                           8.0,  11.0],
      ["Welcome! Why don't you go ahead and introduce yourself?",                      11.0,  14.5],
      ["Of course. Right away.",                                                       14.5,  16.0],
      ["I took a deep breath.",                                                        16.0,  18.0],
      ["Hi everyone, I'm Nga.",                                                        18.0,  20.0],
      ["I'm currently living in Da Nang.",                                             20.0,  22.5],
      ["I work as a freelancer, so my schedule is pretty flexible.",                   22.5,  26.0],
      ["In my free time, I usually hit the gym.",                                      26.0,  29.0],
      ["Not bad, I thought.",                                                          29.0,  31.0],
      ["The club owner nodded.",                                                       31.0,  33.0],
      ["That's great. What made you join us?",                                         33.0,  36.0],
      ["Good question.",                                                               36.0,  37.5],
      ["Well, I said, I realized that every time someone says, Tell me about yourself, my brain just freezes.", 37.5, 43.0],
      ["So I figured it was time to step out of my comfort zone.",                     43.0,  47.0],
      ["No one laughed.",                                                              47.0,  49.0],
      ["One member said, Trust me, we've all been there.",                             49.0,  52.5],
      ["I smiled.",                                                                    52.5,  54.0],
      ["Okay, that makes me feel better.",                                             54.0,  56.5],
      ["By the end of the session, I was chatting with two new friends like it was no big deal.", 56.5, 61.0],
      ["That night, I thought about something simple.",                                61.0,  64.0],
      ["You don't need perfect grammar to connect with people.",                       64.0,  68.0],
      ["You just need the courage to speak up.",                                       68.0,  72.0],
    ]
  },
  2: {
    id: 2,
    title: "A Small Speech for Women's Day",
    emoji: "🌸",
    audio: "topic2.mp3",
    sentences: [
      ["Today, on this special occasion, I want to take a moment to honor every woman in this room.", 0.0, 5.0],
      ["Women carry incredible strength — not just physically, but emotionally and spiritually.",     5.0, 10.0],
      ["Throughout history, women have broken barriers, shattered ceilings, and paved the way.",     10.0, 15.0],
      ["To every mother who woke up early and stayed up late — thank you.",                          15.0, 19.0],
      ["To every daughter who dared to dream — keep going.",                                         19.0, 23.0],
      ["To every colleague who brought her whole self to work — you inspire us.",                    23.0, 27.0],
      ["Women's Day is not just one day — it's a reminder that we celebrate you every single day.",  27.0, 33.0],
      ["So here's to the women who lift others while climbing themselves.",                           33.0, 37.0],
      ["Happy Women's Day to all the remarkable women here today!",                                  37.0, 41.0],
    ]
  },
  3: {
    id: 3,
    title: "Talking about Family",
    emoji: "👨‍👩‍👧‍👦",
    audio: "topic3.mp3",
    sentences: [
      ["I come from a pretty close-knit family of five people.",                        0.0,  4.0],
      ["My father is a retired teacher, and my mother runs a small bakery.",            4.0,  9.0],
      ["I have one older brother and one younger sister.",                              9.0, 13.0],
      ["My brother lives abroad now, so we mostly keep in touch through video calls.", 13.0, 18.0],
      ["My sister and I are very close — we talk almost every day.",                   18.0, 22.0],
      ["During holidays, we always try to get together for big family meals.",         22.0, 27.0],
      ["My grandmother lives with us too, and she's the heart of our family.",         27.0, 32.0],
      ["She always has a story to tell and a warm meal waiting.",                      32.0, 36.0],
      ["Family means everything to me — they are my biggest support system.",          36.0, 41.0],
    ]
  },
  4: {
    id: 4,
    title: "Inviting a Guest Home",
    emoji: "🏠",
    audio: "Topic4.mp3",
    sentences: [
      ["After the sharing time, the club owner smiled at me.",                               0.00,  4.40],
      ["Rose, she said, your family sounds interesting.",                                    4.40,  9.24],
      ["I felt a little shy, but I smiled.",                                                 9.24, 13.28],
      ["Thank you!",                                                                        13.28, 14.62],
      ["Then she asked, do you live near here?",                                            14.62, 18.82],
      ["Yes, I said. My house is not very far from the club.",                              18.82, 24.40],
      ["She laughed softly.",                                                               24.40, 26.42],
      ["Really? I would love to see your home someday.",                                    26.42, 30.26],
      ["I thought for a moment.",                                                           30.26, 32.56],
      ["Then I said, why don't you visit my house this weekend?",                           32.56, 37.64],
      ["Her eyes lit up.",                                                                  37.64, 40.00],
      ["That sounds lovely!",                                                               40.00, 41.78],
      ["On Saturday afternoon, she came to my house.",                                      41.78, 46.08],
      ["When she arrived, I opened the door and waved.",                                    46.08, 50.02],
      ["Welcome to my house!",                                                              50.02, 52.02],
      ["She smiled and said, thank you for inviting me, Rose.",                             52.02, 56.88],
      ["She looked at the building and said, oh, this house looks quite big.",              56.88, 63.14],
      ["I nodded and explained, yes, my family lives here, but we also rent out some rooms.", 63.14, 71.14],
      ["I began to introduce the house.",                                                   71.14, 74.28],
      ["This is the first floor, I said. A small shop rents this space.",                   74.28, 80.60],
      ["They sell clothes.",                                                                80.60, 82.28],
      ["Then I continued. On the upper floors there are several rooms.",                    82.28, 89.82],
      ["Some students rent rooms here and some small families live here too.",              89.82, 96.00],
      ["Then I said, come, let me show you where my family lives.",                         96.00, 103.50],
      ["We walked upstairs.",                                                              103.50, 106.00],
      ["This is our living room, I explained.",                                            106.00, 110.44],
      ["In the evening, my parents, my sister, and I often sit here and talk.",            110.44, 116.00],
      ["Then I pointed to another room. This is our kitchen.",                             116.00, 121.00],
      ["My mom cooks many delicious meals here.",                                          121.00, 127.66],
      ["Over there is our bathroom. It's small, but we always keep it clean.",             127.66, 132.00],
      ["And we have two bedrooms. They are small, but very cozy.",                         132.00, 136.00],
      ["Near the window, there was a small table with some books.",                        136.00, 140.00],
      ["This is my favorite place, I said. I like to sit here and read.",                  140.00, 144.74],
      ["The club owner smiled warmly.",                                                    144.74, 148.00],
      ["That sounds like a very peaceful moment.",                                         148.00, 153.16],
      ["After the tour, we sat in the living room and drank some tea.",                    153.16, 158.50],
      ["The club owner said, Rose, you introduced your house very clearly in English.",    158.50, 163.50],
      ["I laughed a little.",                                                              163.50, 165.50],
      ["I'm still learning, I said, but I like practicing English with real-life things.", 165.50, 168.74],
      ["She nodded. That's the best way to learn.",                                        168.74, 177.40],
      ["Then she said, next week at the club, maybe everyone can talk about their houses.", 177.40, 183.80],
      ["My eyes lit up. That sounds fun!",                                                 183.80, 186.18],
      ["And suddenly I realized something.",                                               186.18, 189.00],
      ["Sometimes, the best English lesson is simply sharing your life, your home, and your stories with others.", 189.00, 195.54],
    ]
  }
};
